import turtle
turtle.showturtle()
turtle.pendown()
a = input('길이를 입력하세요')
a = float(a)
turtle.right(72)
turtle.forward(a)
turtle.right(144)
turtle.forward(a)
turtle.right(144)
turtle.forward(a)
turtle.right(144)
turtle.forward(a)
turtle.right(144)
turtle.forward(a)
